### ISSUE TITLE
Autocompilation action broken?

### ISSUE THREAD

**Issue by Dexagod** [MellonScholarlyCommunication/spec-collector#1]
I think the autocompilation broken?
I pushed it manually on the gh-pages branch at the moment, but that will not auto update on future commits i think.
@mielvds Can you describe how to exactly create such a gh action?

**Comment by mielvds** [comment]
Fixed with https://github.com/MellonScholarlyCommunication/spec-collector/commit/1f3fdecfe8a80d7582e3fb5083db2d2c7814eeda 

Note that your header metadata still points to `spec-eventlog`
